### ISSUE TITLE
Simplify & prevent potential security issue

### ISSUE THREAD

**Issue by chickahoona** [JanMikes/gitlab-ci-push-to-gcr#4]
Instead of 

```
deploy:
  stage: deploy
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo $GOOGLE_CLOUD_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - cat /tmp/$CI_PIPELINE_ID.json | docker login -u _json_key --password-stdin https://eu.gcr.io
  script:
    - docker pull $GITLAB_IMAGE:$CI_COMMIT_SHA
    - docker tag $GITLAB_IMAGE:$CI_COMMIT_SHA $GCR_IMAGE:latest
    - docker push $GCR_IMAGE
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json
``` 

you should be able to simplify that to:

```
deploy:
  stage: deploy
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://eu.gcr.io
  script:
    - docker pull $GITLAB_IMAGE:$CI_COMMIT_SHA
    - docker tag $GITLAB_IMAGE:$CI_COMMIT_SHA $GCR_IMAGE:latest
    - docker push $GCR_IMAGE
```

That way you don't need an `after_script` section and avoid exposing any credentials in a potentially with other users shared /tmp folder :(
